2009-11-05  Sancho Lerena <slerena@gmail.com>
        * pandora_agent_installer: Added a common installer for all systems.

        * Deleted daemon script for all systems, creaded a general one.

        * Modified HPUX to HP-UX directory.

        * Updated some .conf



git-svn-id: https://svn.code.sf.net/p/pandora/code/trunk@2087 c3f86ba8-e40f-0410-aaad-9ba5e7f4b01f

diff --git a/pandora_agents/unix/pandora_agent_installer b/pandora_agents/unix/pandora_agent_installer
--- a/pandora_agents/unix/pandora_agent_installer
+++ b/pandora_agents/unix/pandora_agent_installer
@@ -1,179 +1,274 @@
-#!/bin/bash
+#!/bin/sh
 
-# Pandora FMS Agent Installer (c) 2008-2009 Artica ST
-# Linux Version (generic), for SuSe and Debian/Ubuntu only
-# other Linux distros could not work properly without modifications
+# **********************************************************************
+# Pandora FMS Agent Installer for Unix (generic installer)
+# (c) 2008-2009 Artica ST
+# (c) 2008-2009 Sancho Lerena <slerena@gmail.com>
+# 
+# This is a generic installer for all Unix-like systems.(AIX, HP-UX, SunOS, Linux)
 # Please see http://www.pandorafms.org
-# v3.0 Build 090810
+# v3.0 Build 091103
 # This code is licensed under GPL 2.0 license.
 # **********************************************************************
 
-PI_VERSION=3.0
-PANDORA_BIN=/usr/bin/pandora_agent
+PI_VERSION=3.0.0
+PI_BUILD=091105
+OS_NAME=`uname -s`
+
 PANDORA_HOME=/usr/share/pandora_agent
+PANDORA_BIN=/usr/bin/pandora_agent
 PANDORA_TEMP=/var/spool/pandora
 PANDORA_CFG=/etc/pandora
-PANDORA_LOG=/var/log/pandora/pandora_agent.log
-PANDORA_STARTUP=/etc/init.d/pandora_agent_daemon
+PANDORA_LOG_DIR=/var/log/pandora
+PANDORA_LOG=pandora_agent.log
 TENTACLE=/usr/bin/tentacle_client
-PANDORA_CFG_FILE=/etc/pandora/pandora_agent.conf
-
 FORCE=0
+USE_LINKS=0
+
 LOG_TIMESTAMP=`date +"%Y/%m/%d %H:%M:%S"`
 
 MODE=$1
 
+if [ ! -z "$2" ]
+then
+	PANDORA_HOME=$2
+fi
+
+# Check for Perl 5.8.x available
+PERL_VERSION=`perl -v | egrep 'v5.8|v5.9|v5.1[0-9]' | grep perl`
+
+if [ -z "$PERL_VERSION" ]
+then
+	echo "Perl 5.8.x is not detected. This is required for Pandora FMS"
+	echo "Detected: $PERL_VERSION "
+	echo "Aborting install..."
+	exit 2
+fi
+
+UNIX_KIND=`uname -s`
+if [ -z "`echo Linux HP-UX SunOS AIX Solaris | grep \"$UNIX_KIND\"`" ]
+then
+	echo "This system: '$UNIX_KIND' is not supported by this script"
+	echo "Please make the install yourself as it's described in documentation"
+	exit 1
+fi
+
+
+# check for root to do the install
+if [ -z "`id | grep \"uid=0(root)\"`" ]
+then
+	echo "You need to be root to do the install. Please made a manual install"
+	echo "if you want to install Pandora FMS agent without root"
+	echo " "
+	echo "Aborting install"
+	exit 2
+fi
+
 if [ ! -f "pandora_agent" ]
 then
 	echo " "
-	echo "You need to place pandora_agent file on main distribution directory before install"
+	echo "Execute installer from the directory where you have your files. For example:"
+	echo " "
+	echo "   cd /tmp/pandora_install "
+	echo "   ./pandora_agent_installer --install"
+	echo "   ./pandora_agent_installer --install-with-links /var/opt/PandoraFMS"
 	echo " "
 	exit 1
 fi
 
-uninstall  {
-        echo "Removing Pandora FMS Agent..."
-        rm -Rf $PANDORA_BIN
-        rm -Rf $PANDORA_TEMP
-        rm -Rf $PANDORA_CFG_FILE
-        rm -Rf $PANDORA_STARTUP
-        rm -Rf $PANDORA_HOME
-        rm -Rf $PANDORA_LOG
-		rm -Rf $TENTACLE
-        echo "Done"
+uninstall () {
+	echo "Removing Pandora FMS Agent..."
+	rm -Rf $PANDORA_BIN
+	rm -Rf $PANDORA_TEMP
+	rm -Rf $PANDORA_CFG/pandora_agent.conf
+	
+	rm -Rf /etc/init.d/pandora_agent_daemon 2> /dev/null
+	rm -Rf /sbin/init.d/pandora_agent_daemon 2> /dev/null
+	rm -Rf /etc/rc.pandora_agent_daemon 2> /dev/null
+	rm -Rf /etc/rc?.d/S90pandora_agent_daemon 2> /dev/null
+	rm -Rf /sbin/rc?.d/S90pandora_agent_daemon 2> /dev/null
+	
+	rm -Rf $PANDORA_HOME
+	rm -Rf $PANDORA_LOG_DIR
+	rm -Rf $TENTACLE
+
+	# Skip delete of /etc/pandora if exists configuration of a server
+	if [ ! -f /etc/pandora/pandora_server.conf ]
+	then
+		rm -Rf /etc/pandora
+	fi
+
+	echo "If you install Pandora FMS agent in a custom directory, you should"
+	echo " delete it yourself with command rm -Rf <yourdir>, for example:"
+	echo " "
+	echo "    rm -Rf /opt/software/pandora"
+	echo " "
+	echo "Done"
 }
 
 install () {
 
-		OS_VERSION=`uname -r`
-		OS_NAME=`uname -s`
-		
-		OLDFILENAMETMP=`date +"%Y-%m-%d"`
-		
-		echo "Detecting Unix distribution: $OS_NAME version $OS_VERSION"
-		
-        if [ -f $PANDORA_HOME ] && [ "$FORCE" = "0" ]
-        then
-                echo "Seems that default dir already exists. Please use --force to"
-                echo "force installer to install on $PANDORA_HOME"
-                exit
-        else
-                echo "Checking default dir $PANDORA_HOME..."
-        fi
+	OS_VERSION=`uname -r`
+	OS_NAME=`uname -s`
+	OLDFILENAMETMP=`date +"%Y-%m-%d"`
+	echo "Detecting Unix distribution: $OS_NAME version $OS_VERSION"
+	if [ -f $PANDORA_HOME ] && [ "$FORCE" = "0" ]
+	then
+		echo "Seems that default dir already exists. Please use --force to"
+		echo "force installer to install on $PANDORA_HOME"
+		exit
+	else
+		echo "Checking default dir $PANDORA_HOME..."
+	fi
 
-        if [ -f $PANDORA_BIN ] && [ "$FORCE" = "0" ]
-        then
-                echo "Seems that $PANDORA_BIN already exists. Please use --force to"
-                echo "force installer to reinstall overwriting it"
-                echo " "
-                exit
-        else
-                echo "Checking Pandora FMS Agent on $PANDORA_BIN...."
-        fi
-
-        # Create directories
-        echo "Creating Pandora FMS Agent home directory at $PANDORA_HOME ..."
-        mkdir $PANDORA_HOME 2> /dev/null
-        mkdir $PANDORA_TEMP 2> /dev/null
-        mkdir $PANDORA_TEMP/data_out 2> /dev/null
-        mkdir $PANDORA_CFG 2> /dev/null
-		mkdir /var/log/pandora 2> /dev/null
-
-        # Create logfile
-        if [ ! -z "`touch $PANDORA_LOG`" ]
-        then
-                echo "Seems to be a problem generating logfile ($PANDORA_LOG) please check it";
-        else
-                echo "Creating logfile at $PANDORA_LOG..."
-        fi
-
-        echo "$LOG_TIMESTAMP Pandora FMS installer has created this file at startup" > $PANDORA_LOG
-
-        # Copying agent and securing it
-        echo "Copying Pandora FMS Agent to $PANDORA_BIN..."
-        cp pandora_agent $PANDORA_BIN
-        chmod 700 $PANDORA_BIN
-	
-		echo "Copying Pandora FMS Agent contrib dir to $PANDORA_HOME/..."
-        cp pandora_agent_daemon $PANDORA_HOME
-
-        echo "Copying Pandora FMS Agent configuration file to $PANDORA_HOME/pandora_agent.conf..."
-        if [ -e /etc/pandora/pandora_agent.conf ]
-        then
-        	cat /etc/pandora/pandora_agent.conf > /etc/pandora/pandora/pandora_agent.conf.$OLDFILENAMETMP
-        	echo "Backing up old configuration file to /etc/pandora_agent.conf.$OLDFILENAMETMP"
-        fi
-        
-        echo "Copying default agent configuration to $PANDORA_HOME/pandora_agent.conf"
-        cp $OS_NAME/pandora_agent.conf $PANDORA_HOME/pandora_agent.conf
-        chmod 600 $PANDORA_HOME/pandora_agent.conf
-
-        echo "Copying Pandora FMS Agent plugins to $PANDORA_HOME/plugins..."
-        cp -r plugins $PANDORA_HOME
-        chmod -R 700 $PANDORA_HOME/plugins
-
-		echo "Copying tentacle client to $TENTACLE"
-		cp tentacle_client $TENTACLE
-
-        echo "Linking Pandora FMS Agent plugins directory to $PANDORA_CFG/plugins..."
-        rm $PANDORA_CFG/plugins 2> /dev/null
-        ln -s $PANDORA_HOME/plugins $PANDORA_CFG 2> /dev/null
-
-        echo "Linking Pandora FMS Agent configuration to $PANDORA_CFG/pandora_agent.conf..."
-        rm $PANDORA_CFG/pandora_agent.conf 2> /dev/null
-        ln -s $PANDORA_HOME/pandora_agent.conf $PANDORA_CFG/pandora_agent.conf 
-        
-        echo "Setting secure permissions and ownership for all Pandora FMS Agent files..."
-        chown -R root $PANDORA_HOME
-        chmod -R 600 $PANDORA_TEMP/data_out
-        chmod 640 $PANDORA_LOG
-        chgrp root $PANDORA_LOG
-
-        echo "Linking start-up daemon script at $PANDORA_STARTUP";
-
-        if [ "$OS_NAME" == "AIX" ]
-        then
-        	cp $OS_NAME/pandora_agent_daemon /etc/rc.pandora_agent_daemon
-        else
-	        cp $OS_NAME/pandora_agent_daemon $PANDORA_STARTUP
-		fi
-		
-		if [ "$OS_NAME" == "AIX" ]
-		then
-	        echo "Linking start-up daemon script to /etc/rc2.d";
-	        ln -s /etc/rc.pandora_agent_daemon /etc/rc2.d/S90pandora_agent
-		else
-			INITLV=`cat /etc/inittab | grep "[0-9]\:initdefault" | cut -f 2 -d ":"`
-			echo "Linking start-up daemon script to /etc/rc.d/rc$INITLV.d";
-	        ln -s /etc/init.d/pandora_agent_daemon /etc/rc.d/rc$INITLV.d/S90pandora_agent
-		fi
-		
-        chown -R root:root $PANDORA_BIN
-        
-        echo "Done."
-        echo " "
-        echo "You have your startup script ready at $PANDORA_STARTUP"
+	if [ -f $PANDORA_BIN ] && [ "$FORCE" = "0" ]
+	then
+		echo "Seems that $PANDORA_BIN already exists. Please use --force to"
+		echo "force installer to reinstall overwriting it"
 		echo " "
-		echo "Tentacle is the default transfer mode since 2.0 version."
-        echo "If you want to use SSH, firstly you need to copy your public SSH keys ($HOME/.ssh/id_dsa)"
-        echo "under /home/pandora/.ssh/authorized_keys on your Pandora FMS Server host"
-        echo "You also need to setup your $PANDORA_CFG/pandora_agent.conf config file"
-        echo " "
-        echo "Take a look of your
-        echo " "
+		exit
+	else
+		echo "Checking Pandora FMS Agent on $PANDORA_BIN...."
+	fi
+
+	echo "Creating Pandora FMS Agent home directory at $PANDORA_HOME ..."
+	mkdir -p $PANDORA_HOME 2> /dev/null
+	
+	# IF USE_LINKS = 1 then append HOME to other paths
+	if [ "$USE_LINKS" = 1 ]
+	then
+		mkdir -p $PANDORA_HOME/$PANDORA_TEMP/data_out 2> /dev/null
+		mkdir -p $PANDORA_LOG_DIR 2> /dev/null
+		
+		ln -s $PANDORA_HOME /etc/pandora
+		ln -s $PANDORA_HOME/$PANDORA_TEMP /var/spool/pandora
+	else
+		# Create directories on /
+		mkdir -p $PANDORA_TEMP/data_out 2> /dev/null
+		mkdir -p $PANDORA_CFG 2> /dev/null
+		mkdir -p $PANDORA_LOG_DIR 2> /dev/null
+	fi
+
+	# Create logfile
+	if [ ! -z "`touch $PANDORA_LOG_DIR/$PANDORA_LOG`" ]
+	then
+		echo "Seems to be a problem generating logfile ($PANDORA_LOG_DIR/$PANDORA_LOG) please check it";
+	else
+		echo "Created logfile at $PANDORA_LOG_DIR/$PANDORA_LOG..."
+	fi
+
+	echo "$LOG_TIMESTAMP Pandora FMS installer has created this file at startup" > $PANDORA_LOG_DIR/$PANDORA_LOG
+
+	# Copying agent and securing it
+	echo "Copying Pandora FMS Agent to $PANDORA_BIN..."
+	cp pandora_agent $PANDORA_BIN
+	chmod 755 $PANDORA_BIN
+	chown root:root $PANDORA_BIN
+	
+	echo "Copying Pandora FMS Agent configuration file to $PANDORA_HOME/pandora_agent.conf..."
+	if [ -f /etc/pandora/pandora_agent.conf ]
+	then
+		cat /etc/pandora/pandora_agent.conf > /etc/pandora/pandora_agent.conf.$OLDFILENAMETMP
+		echo "Backing up old configuration file to /etc/pandora_agent.conf.$OLDFILENAMETMP"
+	fi
+        
+	echo "Copying default agent configuration to $PANDORA_HOME/pandora_agent.conf"
+	cp $OS_NAME/pandora_agent.conf $PANDORA_HOME/pandora_agent.conf
+	chmod 600 $PANDORA_HOME/pandora_agent.conf
+	chown root $PANDORA_HOME/pandora_agent.conf
+
+	echo "Copying Pandora FMS Agent plugins to $PANDORA_HOME/plugins..."
+	cp -r plugins $PANDORA_HOME
+	chmod -R 700 $PANDORA_HOME/plugins
+
+	echo "Copying tentacle client to $TENTACLE"
+	cp tentacle_client $TENTACLE
+	chmod 755 $TENTACLE
+
+	if [ "$USE_LINKS" != 1 ]
+	then
+		echo "Linking Pandora FMS Agent plugins directory to $PANDORA_CFG/plugins..."
+		rm $PANDORA_CFG/plugins 2> /dev/null
+		ln -s $PANDORA_HOME/plugins $PANDORA_CFG/plugins 2> /dev/null
+
+		echo "Linking Pandora FMS Agent configuration to $PANDORA_CFG/pandora_agent.conf..."
+		rm $PANDORA_CFG/pandora_agent.conf 2> /dev/null
+		ln -s $PANDORA_HOME/pandora_agent.conf $PANDORA_CFG/pandora_agent.conf 
+	fi
+
+	echo "Setting secure permissions and ownership for all Pandora FMS Agent files..."
+	chown -R root $PANDORA_HOME
+	chmod -R 600 $PANDORA_TEMP
+	chown root $PANDORA_TEMP
+	chmod 640 $PANDORA_LOG_DIR/$PANDORA_LOG
+	chown root:root $PANDORA_LOG_DIR/$PANDORA_LOG
+
+	echo "Linking start-up daemon script 'pandora_agent_daemon' on $OS_NAME";
+
+	if [ "$OS_NAME" = "AIX" ]
+	then
+		cp pandora_agent_daemon /etc/rc.pandora_agent_daemon		
+		ln -s /etc/rc.pandora_agent_daemon /etc/rc.d/rc2.d/S90pandora_agent_daemon
+		echo "Pandora FMS agent has been included in /etc/rc.d/rc2.d/S90pandora_agent_daemon"
+	fi
+	
+	if [ $OS_NAME = "HP-UX" ]
+	then
+		cp pandora_agent_daemon /sbin/init.d/pandora_agent_daemon
+		ln -s /sbin/init.d/pandora_agent_daemon /sbin/rc3.d/S90pandora_agent_daemon
+		ln -s /sbin/init.d/pandora_agent_daemon /sbin/rc2.d/S90pandora_agent_daemon
+		echo "Pandora FMS agent has been included in /sbin/rcX.d/S90pandora_agent_daemon"
+	fi
+	
+	if [ $OS_NAME = "SunOS" ]
+	then
+		cp pandora_agent_daemon /etc/init.d/pandora_agent_daemon
+		ln -s /etc/init.d/pandora_agent_daemon /etc/rc2.d/S90pandora_agent_daemon
+		echo "Pandora FMS agent has been included in /etc/rc2.d/S90pandora_agent_daemon"
+	fi
+	
+	if [ $OS_NAME = "Linux" ]
+	then
+		cp pandora_agent_daemon /etc/init.d/pandora_agent_daemon
+		if [ -d /etc/rc.d/ ]
+		then
+			ln -s /etc/init.d/pandora_agent_daemon /etc/rc.d/rc2.d/S90pandora_agent
+			ln -s /etc/init.d/pandora_agent_daemon /etc/rc.d/rc3.d/S90pandora_agent
+		else
+			ln -s /etc/init.d/pandora_agent_daemon /etc/rc2.d/S90pandora_agent
+			ln -s /etc/init.d/pandora_agent_daemon /etc/rc2.d/S90pandora_agent
+		fi
+	fi
+
+	echo "Done."
+	echo " "
+	echo "You have your startup script ready at $PANDORA_STARTUP"
+	echo " "
+	echo "Tentacle is the default transfer mode since 2.0 version."
+	echo "If you want to use SSH, firstly you need to copy your public SSH keys "
+	echo " ($HOME/.ssh/id_dsa) under /home/pandora/.ssh/authorized_keys "
+	echo "on your Pandora FMS Server host"
+	echo " "
+	echo "You also need to setup your $PANDORA_CFG/pandora_agent.conf config file"
+	echo " "
+	echo "Check your startup configuration to be sure Pandora FMS Agent is ready "
+	echo "to start automatically when system restarts":
 
 }
 
 help () {
-        echo "     --force-install     To force installation if already installed on system "
-        echo "     --install           To install Pandora FMS Agent on this system"
-        echo "     --uninstall         To uninstall and remove Pandora FMS Agent on this System"
-        echo " "
+    echo "  --force-install      To force installation if already installed on system"
+    echo "  --install            To install Pandora FMS Agent on this system"
+    echo "  --uninstall          To uninstall/remove Pandora FMS Agent on this System"
+    echo "  --install-with-links <base_dir> "
+    echo "                       To install Pandora FMS in a defined dir <base_dir>"
+    echo "                       and set all Pandora FMS directories as links to this"
+    echo " "
 }
 
 # Script banner at start
 echo " "
-echo "Pandora FMS Agent Installer $PI_VERSION (c) 2008-2009 ArticaST"
+echo "Pandora FMS Agent UNIX Installer $PI_VERSION $PI_BUILD (c) 2008-2009 ArticaST"
 echo "This program is licensed under GPL2 Terms. http://pandorafms.com"
 echo " "
 
@@ -190,6 +285,12 @@ case "$MODE" in
         exit
         ;;
 
+'--install-with-links')
+        USE_LINKS=1
+        install
+        exit
+        ;;
+
 '--uninstall')
         uninstall
         exit
@@ -197,5 +298,6 @@ case "$MODE" in
 
 *)
         help
+        ;;
 esac
 
