2009-08-11  Sancho Lerena <slerena@artica.es>
	* linux/pandora_agent_installer: Some fixes and support for Ubuntu/SUSE
	specific installer.
	
	* linux/plugins/grep_log: Support for more than module over the same file.
	
	* linux/pandora_agent_daemon: Fixed problems with PID control, rewrite
	function, now should works on any linux distro. 
	
	* linux/pandora_agent.conf: Added new inventory plugin and minor changes in
	default modules.

	* linux/pandora_agent: Updated version and build 



git-svn-id: https://svn.code.sf.net/p/pandora/code/trunk@1841 c3f86ba8-e40f-0410-aaad-9ba5e7f4b01f

diff --git a/pandora_agents/linux/pandora_agent_daemon b/pandora_agents/linux/pandora_agent_daemon
--- a/pandora_agents/linux/pandora_agent_daemon
+++ b/pandora_agents/linux/pandora_agent_daemon
@@ -1,8 +1,11 @@
 #!/bin/bash
-# Init script for Pandora FMS agent
-# Generic GNU/Linux version
-# Sancho Lerena, <slerena@gmail.com>
-# v3.0
+
+# Pandora FMS Linux Agent, startup script
+# Copyright (c) 2006-2009 Artica ST, <info@artica.es>
+# Linux Version (generic), for SuSe and Debian/Ubuntu.
+# other Linux distros could not work properly without modifications
+# v3.0 Build 090810
+# http://www.pandorafms.com
 
 ### BEGIN INIT INFO
 # Provides: pandora_agent
@@ -16,8 +19,14 @@
 PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
 PANDORA_PATH=/etc/pandora
 DAEMON=/usr/bin/pandora_agent
-PIDFILE=/var/run/pandora_agent.pid
 LOGFILE=/var/log/pandora_agent.log
+
+# This function replace pidof, not working in the same way in different linux distros
+
+function pidof_pandora () (
+	PANDORA_PID=`ps aux | grep $DAEMON | grep -v grep | head -1 | awk '{ print $2 }'`
+	echo $PANDORA_PID
+)
 
 if [ ! -f $DAEMON ]
 then
@@ -26,37 +35,51 @@ then
 fi
 
 case "$1" in
-  start)
-        PANDORA_PID=$(pidof -x $DAEMON)
-	if [ ! -z "$PANDORA_PID" ]
-	then
-            echo "Pandora FMS Agent is currently running on this machine with PID $PANDORA_PID"
-            echo "Cannot launch again. Aborting."
-            exit 1
-        fi
-        nohup $DAEMON $PANDORA_PATH 2> $LOGFILE & PANDORA_PID=$!
-        echo $PANDORA_PID > $PIDFILE
-	echo "Pandora FMS Agent is now running with PID $PANDORA_PID"
-        ;;
-  stop)
-	PANDORA_PID=$(pidof -x $DAEMON)
-        if [ -z "$PANDORA_PID" ]
-        then
-		echo "Pandora FMS Agent is not running, cannot stop it. Aborting now..."
-		exit 1
-        else
-		echo "Stopping Pandora Agent."
-		kill $PANDORA_PID > /dev/null 2>&1
-	        rm -f $PANDORA_PID        
-	fi
-        ;;
-  force-reload|restart)
-        $0 stop
-		sleep 3
-        $0 start
-        ;;
-  *)
-        echo "Uso: /etc/init.d/pandora_agent_daemon {start|stop|restart|force-reload}"
+	start)
+		PANDORA_PID=`pidof_pandora`
+		if [ ! -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Agent is currently running on this machine with PID $PANDORA_PID"
+			echo "Cannot launch again. Aborting."
+			exit 1
+		fi
+		nohup $DAEMON $PANDORA_PATH 2> $LOGFILE & 
+		sleep 1
+		PANDORA_PID=`pidof_pandora`
+		echo "Pandora FMS Agent is now running with PID $PANDORA_PID"
+	;;
+	
+	stop)
+		PANDORA_PID=`pidof_pandora`
+		if [ -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Agent is not running, cannot stop it. Aborting now..."
+			exit 1
+		else
+			echo "Stopping Pandora Agent."
+			kill $PANDORA_PID > /dev/null 2>&1        
+		fi
+	;;
+
+	status)
+		PANDORA_PID=`pidof_pandora`	
+		if [ -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Agent is not running."
+		else
+			echo "Pandora FMS Agent is running with PID $PANDORA_PID."
+		fi
+		exit 0
+	;;
+
+	force-reload|restart)
+		$0 stop
+		sleep 2
+		$0 start
+	;;
+	
+	*)
+        echo "Uso: /etc/init.d/pandora_agent_daemon {start|stop|restart|status|force-reload}"
         exit 1
 esac
 
