2009-08-11  Sancho Lerena <slerena@artica.es>
	* pandora_server: Using new method to get PID of process, compatible with
	any distro (SUSE problems reported). Removed old stuff and updated headers.
	
	* pandora_server_installer: A lot of improvementes and added separated code
	for Ubuntu/Debian and SUSE targets. Fixed some minor bugs reported.
	
	* bin/pandora_server: Added a new die handled for manage crashes and report
	more information into logs and console on startup. This helps to determine
	some common problems.
	
	* Config.pm: Updated version number.
	
	* util/tentacle_serverd: Fixed startup script to work also in SUSE. New
	code for getpid compatible with all distros.

	* Makefile.PL,  NetworkServer.pm: Removed Net::Ping dependency, 
	not used anymore. Pending to remove Date::Manip from pandora_db script.



git-svn-id: https://svn.code.sf.net/p/pandora/code/trunk@1840 c3f86ba8-e40f-0410-aaad-9ba5e7f4b01f

diff --git a/pandora_server/pandora_server b/pandora_server/pandora_server
--- a/pandora_server/pandora_server
+++ b/pandora_server/pandora_server
@@ -1,18 +1,28 @@
 #!/bin/bash
 
 # Pandora FMS Server, startup script
-# Copyright (c) 2006-2008 Sancho Lerena, <slerena@gmail.com>
-# Linux Version (generic)
-# v2.1 Build 081030
+# Copyright (c) 2006-2009 Sancho Lerena, <sancho.lerena@artica.es>
+# Linux Version (generic), for SuSe and Debian/Ubuntu.
+# other Linux distros could not work properly without modifications
+# v3.0 Build 090810
 # http://www.pandorafms.com
 # chkconfig: 23 99 99
 # description: Manages starting/stopping of server
 
 # Configurable path and filenames
+
 PANDORA_HOME="/etc/pandora/pandora_server.conf"
 PANDORA_PID_PATH="/var/run"
 PANDORA_PID=$PANDORA_PID_PATH/pandora_server.pid
 PANDORA_DAEMON=/usr/local/bin/pandora_server
+
+
+# This function replace pidof, not working in the same way in different linux distros
+
+function pidof_pandora () (
+	PANDORA_PID=`ps aux | grep $PANDORA_DAEMON | grep -v grep | tail -1 | awk '{ print $2 }'`
+	echo $PANDORA_PID
+)
 
 # Main script
 
@@ -29,48 +39,55 @@ then
 fi
 
 case "$1" in
-  start)
-	OLD_PATH="`pwd`"
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-	if [ ! -z $PANDORA_PID ]
-	then
-		echo "Pandora FMS Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
-		exit 1	
-	else
-	rm -f $PANDORA_PID
-	fi
+	start)
+		PANDORA_PID=`pidof_pandora`
+		if [ ! -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
+			exit 1
+		fi
 	
-	$PANDORA_DAEMON $PANDORA_HOME -D
-	sleep 1
+		$PANDORA_DAEMON $PANDORA_HOME -D
+		sleep 2
 
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-	if [ ! -z "$PANDORA_PID" ]
-	then
-		echo "Pandora Server is now running with PID $PANDORA_PID"
-	else
-		echo "Cannot start Pandora FMS Server. Aborted."
-	fi
-	cd "$OLD_PATH"
-		;;
-  stop)
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-	if [ -z $PANDORA_PID ]
-	then
-		echo "Pandora FMS Server is not running, cannot stop it."
-		exit 1
-	else
-		echo "Stopping Pandora FMS Server"
+		PANDORA_PID=`pidof_pandora`
+		if [ ! -z "$PANDORA_PID" ]
+		then
+			echo "Pandora Server is now running with PID $PANDORA_PID"
+		else
+			echo "Cannot start Pandora FMS Server. Aborted."
+			echo "Check Pandora FMS log files at '/var/log/pandora/pandora_server.log'"
+		fi
+	;;
+		
+	stop)
+		PANDORA_PID=`pidof_pandora`
+		if [ -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Server is not running, cannot stop it."
+			exit 1
+		else
+			echo "Stopping Pandora FMS Server"
 			kill $PANDORA_PID > /dev/null 2>&1
-			rm -f $PANDORA_PID
-	fi
-		;;
+		fi
+	;;
+	status)
+		PANDORA_PID=`pidof_pandora`
+		if [ -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Server is not running."
+		else
+			echo "Pandora FMS Server is running with PID $PANDORA_PID."
+		fi
+		exit 0
+        ;;
   force-reload|restart)
 		$0 stop
-		sleep 2
+		sleep 3
 		$0 start
 		;;
   *)
-		echo "Usage: pandora_server {start|stop|restart}"
+		echo "Usage: pandora_server { start | stop | restart | status }"
 		exit 1
 esac
 
