2008-03-11 Manuel Arostegui <marostegui@artica.es>
        * pandora_server, pandora_network, pandora_recon:
        Added pidof checking to check the PID of the process.



git-svn-id: https://svn.code.sf.net/p/pandora/code/trunk@746 c3f86ba8-e40f-0410-aaad-9ba5e7f4b01f

diff --git a/pandora_server/pandora_server b/pandora_server/pandora_server
--- a/pandora_server/pandora_server
+++ b/pandora_server/pandora_server
@@ -7,7 +7,7 @@
 
 # Configurable path and filenames
 PANDORA_HOME="/etc/pandora/pandora_server.conf"
-PANDORA_PID_PATH="/var/run/pandora"
+PANDORA_PID_PATH="/var/run"
 PANDORA_PID=$PANDORA_PID_PATH/pandora_dataserver.pid
 PANDORA_DAEMON=/usr/local/bin/pandora_server
 
@@ -28,42 +28,37 @@ fi
 case "$1" in
   start)
 	OLD_PATH="`pwd`"
-	if [ -f $PANDORA_PID ]
+	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+	if [ ! -z $PANDORA_PID ]
 	then
-		CHECK_PID=`cat $PANDORA_PID`
-		CHECK_PID_RESULT=`ps aux | grep -v grep | grep "$CHECK_PID" | grep "pandora_server" | wc -l`
-		if [ $CHECK_PID_RESULT == 1 ]
-		then
-			echo "Pandora FMS Data Server is currently running on this machine with PID ($CHECK_PID). Aborting now..."
-			exit
-		fi
+		echo "Pandora FMS Data Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
+		exit 1	
+	else
+	rm -f $PANDORA_PID
 	fi
 	
 	$PANDORA_DAEMON $PANDORA_HOME -D
 	sleep 1
 
-	MYPID=`ps aux | grep "$PANDORA_DAEMON" | grep -v grep | tail -1 | awk '{print $2}'`
-	if [ ! -z "$MYPID" ]
+	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+	if [ ! -z "$PANDORA_PID" ]
 	then
-		echo $MYPID > $PANDORA_PID
-		echo "Pandora Data Server is now running with PID $MYPID"
+		echo "Pandora Data Server is now running with PID $PANDORA_PID"
 	else
 		echo "Cannot start Pandora FMS Data Server. Aborted."
 	fi
 	cd "$OLD_PATH"
         ;;
   stop)
-	if [ -f $PANDORA_PID ]
+	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+	if [ -z $PANDORA_PID ]
 	then
-	   echo "Stopping Pandora FMS Data Server"
-	   PID_2=`cat $PANDORA_PID`
-	   if [ ! -z "`ps -F -p $PID_2 | grep -v grep | grep 'pandora_server' `" ]
-           then
-	       kill `cat $PANDORA_PID` 2> /dev/null > /dev/null
-	   fi
-           rm -f $PANDORA_PID
+          echo "Pandora FMS Data Server is not running, cannot stop it."
+          exit 1
 	else
-	  echo "Pandora FMS Data Server is not running, cannot stop it."
+	   echo "Stopping Pandora FMS Data Server"
+           kill $PANDORA_PID > /dev/null 2>&1
+           rm -f $PANDORA_PID
 	fi
         ;;
   force-reload|restart)
