2008-09-08  Raul Mateos <raulofpandora@gmail.com> 	* pandora_*: Updated headers with build and new URL, better style
git-svn-id: https://svn.code.sf.net/p/pandora/code/trunk@1088 c3f86ba8-e40f-0410-aaad-9ba5e7f4b01f

diff --git a/pandora_server/pandora_network b/pandora_server/pandora_network
--- a/pandora_server/pandora_network
+++ b/pandora_server/pandora_network
@@ -1,9 +1,10 @@
 #!/bin/bash
 
 # Pandora FMS Network Server, startup script
-# Sancho Lerena, <slerena@gmail.com>
+# Copyright (c) 2006-2008 Sancho Lerena, <slerena@gmail.com>
 # Linux Version (generic)
-# v1.3 Build 070731
+# v2.0 Build 080903
+# http://www.pandorafms.com
 
 # Configurable path and filenames
 PANDORA_HOME="/etc/pandora/pandora_server.conf"
@@ -21,52 +22,52 @@ fi
 
 if [ ! -f $PANDORA_DAEMON ]
 then
-        echo "Pandora FMS Network Server not found, please check setup and read manual"
-        exit
+	echo "Pandora FMS Network Server not found, please check setup and read manual"
+	exit
 fi
 
 case "$1" in
-  start)
-	OLD_PATH="`pwd`"
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-        if [ ! -z $PANDORA_PID ]
-	then
+	start)
+		OLD_PATH="`pwd`"
+		PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+			if [ ! -z $PANDORA_PID ]
+		then
 			echo "Pandora FMS Network Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
 			exit 1
-	else
-	rm -f $PANDORA_PID
-	fi
-	
-	$PANDORA_DAEMON $PANDORA_HOME -D
-	sleep 1
+		else
+		rm -f $PANDORA_PID
+		fi
+		
+		$PANDORA_DAEMON $PANDORA_HOME -D
+		sleep 1
 
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-	if [ ! -z "$PANDORA_PID" ]
-	then
-		echo "Pandora Network Server is now running with PID $PANDORA_PID"
-	else
-		echo "Cannot start Pandora FMS Network Server. Aborted."
-	fi
-	cd "$OLD_PATH"
-        ;;
-  stop)
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-	if [ -z $PANDORA_PID ]
-	then
-	   echo "Pandora FMS Network Server is not running, cannot stop it."
-	   exit 1
-	else
-	   echo "Stopping Pandora FMS Network Server"
-           kill $PANDORA_PID > /dev/null 2>&1
-           rm -f $PANDORA_PID
-	fi
-        ;;
-  force-reload|restart)
-        $0 stop
-        $0 start
-        ;;
-  *)
-        echo "Usage: pandora_network {start|stop|restart}"
-        exit 1
+		PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+		if [ ! -z "$PANDORA_PID" ]
+		then
+			echo "Pandora Network Server is now running with PID $PANDORA_PID"
+		else
+			echo "Cannot start Pandora FMS Network Server. Aborted."
+		fi
+		cd "$OLD_PATH"
+	        ;;
+	stop)
+		PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+		if [ -z $PANDORA_PID ]
+		then
+			echo "Pandora FMS Network Server is not running, cannot stop it."
+			exit 1
+		else
+			echo "Stopping Pandora FMS Network Server"
+				kill $PANDORA_PID > /dev/null 2>&1
+				rm -f $PANDORA_PID
+		fi
+			;;
+	force-reload|restart)
+		$0 stop
+		$0 start
+		;;
+	*)
+		echo "Usage: pandora_network {start|stop|restart}"
+		exit 1
 esac
 
diff --git a/pandora_server/pandora_plugin b/pandora_server/pandora_plugin
--- a/pandora_server/pandora_plugin
+++ b/pandora_server/pandora_plugin
@@ -1,15 +1,16 @@
 #!/bin/bash
 
 # Pandora FMS Plugin Server, startup script
-# Sancho Lerena, <slerena@gmail.com>
+# Copyright (c) 2006-2008 Sancho Lerena, <slerena@gmail.com>
 # Linux Version (generic)
-# 2.0 Build 080620
+# v2.0 Build 080903
+# http://www.pandorafms.com
 
 # Configurable path and filenames
 PANDORA_HOME="/etc/pandora/pandora_server.conf"
 PANDORA_PID_PATH="/var/run"
 PANDORA_PID=$PANDORA_PID_PATH/pandora_plugin.pid
-PANDORA_DAEMON=/usr/bin/pandora_plugin
+PANDORA_DAEMON=/usr/local/bin/pandora_plugin
 
 # Main script
 
@@ -21,50 +22,50 @@ fi
 
 if [ ! -f $PANDORA_DAEMON ] 
 then
-        echo "Pandora FMS Plugin Server not found, please check setup and read manual"
-        exit
+	echo "Pandora FMS Plugin Server not found, please check setup and read manual"
+	exit
 fi
 
 case "$1" in
-  start)
-	OLD_PATH="`pwd`"
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-        if [ ! -z $PANDORA_PID ]
-	then
-		echo "Pandora FMS Plugin Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
-		exit 1
-	fi
-	
-	$PANDORA_DAEMON $PANDORA_HOME -D
-	sleep 1
+	start)
+		OLD_PATH="`pwd`"
+		PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+			if [ ! -z $PANDORA_PID ]
+		then
+			echo "Pandora FMS Plugin Server is currently running on this machine with PID ($PANDORA_PID). Aborting now..."
+			exit 1
+		fi
 
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-        if [ ! -z "$PANDORA_PID" ]
-	then
-		echo "Pandora FMS Plugin Server is now running with PID $PANDORA_PID"
-	else
-		echo "Cannot start Pandora FMS Plugin Server. Aborted."
-	fi
-	cd "$OLD_PATH"
-        ;;
-  stop)
-	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
-        if [ -z $PANDORA_PID ]
-	then
-		echo "Pandora FMS Plugin Server is not running, cannot stop it."
-		exit 1	
-	else
-	   	echo "Stopping Pandora FMS Plugin Server"
-           	kill $PANDORA_PID > /dev/null 2>&1
-           	rm -f $PANDORA_PID
-	fi
-        ;;
-  force-reload|restart)
-        $0 stop
-        $0 start
-        ;;
-  *)
-        echo "Usage: pandora_plugin {start|stop|restart}"
-        exit 1
+		$PANDORA_DAEMON $PANDORA_HOME -D
+		sleep 1
+
+		PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+			if [ ! -z "$PANDORA_PID" ]
+		then
+			echo "Pandora FMS Plugin Server is now running with PID $PANDORA_PID"
+		else
+			echo "Cannot start Pandora FMS Plugin Server. Aborted."
+		fi
+		cd "$OLD_PATH"
+			;;
+	stop)
+		PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
+			if [ -z $PANDORA_PID ]
+		then
+			echo "Pandora FMS Plugin Server is not running, cannot stop it."
+			exit 1	
+		else
+			echo "Stopping Pandora FMS Plugin Server"
+				kill $PANDORA_PID > /dev/null 2>&1
+				rm -f $PANDORA_PID
+		fi
+	        ;;
+	force-reload|restart)
+		$0 stop
+		$0 start
+		;;
+	*)
+		echo "Usage: pandora_plugin {start|stop|restart}"
+		exit 1
 esac
 
diff --git a/pandora_server/pandora_server b/pandora_server/pandora_server
--- a/pandora_server/pandora_server
+++ b/pandora_server/pandora_server
@@ -1,9 +1,10 @@
 #!/bin/bash
 
-# Pandora Data Server, startup script
-# Sancho Lerena, <slerena@gmail.com>
-# Linux Version (generico)
-# v1.3 Build 070802
+# Pandora FMS Data Server, startup script
+# Copyright (c) 2006-2008 Sancho Lerena, <slerena@gmail.com>
+# Linux Version (generic)
+# v2.0 Build 080903
+# http://www.pandorafms.com
 
 # Configurable path and filenames
 PANDORA_HOME="/etc/pandora/pandora_server.conf"
@@ -21,8 +22,8 @@ fi
 
 if [ ! -f $PANDORA_DAEMON ]
 then
-        echo "Pandora FMS Data Server not found, please check setup and read manual"
-        exit
+	echo "Pandora FMS Data Server not found, please check setup and read manual"
+	exit
 fi
 
 case "$1" in
@@ -48,25 +49,25 @@ case "$1" in
 		echo "Cannot start Pandora FMS Data Server. Aborted."
 	fi
 	cd "$OLD_PATH"
-        ;;
+		;;
   stop)
 	PANDORA_PID=$(pidof -x $PANDORA_DAEMON)
 	if [ -z $PANDORA_PID ]
 	then
-          echo "Pandora FMS Data Server is not running, cannot stop it."
-          exit 1
+		echo "Pandora FMS Data Server is not running, cannot stop it."
+		exit 1
 	else
-	   echo "Stopping Pandora FMS Data Server"
-           kill $PANDORA_PID > /dev/null 2>&1
-           rm -f $PANDORA_PID
+		echo "Stopping Pandora FMS Data Server"
+			kill $PANDORA_PID > /dev/null 2>&1
+			rm -f $PANDORA_PID
 	fi
-        ;;
+		;;
   force-reload|restart)
-        $0 stop
-        $0 start
-        ;;
+		$0 stop
+		$0 start
+		;;
   *)
-        echo "Usage: pandora_server {start|stop|restart}"
-        exit 1
+		echo "Usage: pandora_server {start|stop|restart}"
+		exit 1
 esac
 
